PRAGMA foreign_keys = "ON";
insert into users(email,name)values('dolly@ex.com','dolly');
insert into users(email,name)values("ankur@ex.com",'ankur');
insert into users(email,name)values("dino@ex.com",'dino');
insert into login(email,password)values("ankur@ex.com",'ankur12345');
insert into login(email,password)values('dolly@ex.com','dolly12345');
insert into topics(name,description,start_time,email)values("cricket","sachin tendulkar",123454,"dolly@ex.com");
insert into topics(name,description,start_time,email)values("music","ar raheman",45555,"dolly@ex.com");
insert into topics(name,description,start_time,email)values("racing","mikha singh",124342,"dolly@ex.com");
insert into topics(name,description,start_time,email)values("boxing","merry com",12454,"dolly@ex.com");
insert into topics(name,description,start_time,email)values("chess"," v.anad",14343,"dolly@ex.com");
insert into topics(name,description,start_time,email)values("commedy","kapil sharma",55555,"dino@ex.com");
insert into comments(content,topic_id,time,email)values("hiiii",1,12345,"dolly@ex.com");
insert into comments(content,topic_id,time,email)values("hello",1,12346,"ankur@ex.com");
insert into comments(content,topic_id,time,email)values("hello",2,12347,"dolly@ex.com");
insert into comments(content,topic_id,time,email)values("hello",3,12355,"dolly@ex.com");
insert into comments(content,topic_id,time,email)values("hello",4,125555,"dolly@ex.com");
insert into comments(content,topic_id,time,email)values("hello",5,123565,"dolly@ex.com");
insert into comments(content,topic_id,time,email)values("hello",5,123556,"ankur@ex.com");
insert into comments(content,topic_id,time,email)values("hello",6,12356,"dino@ex.com");
update users set start_topic_ids ="[1]" where email ='dolly@ex.com';
update users set join_topic_ids ="[1]" where email ='ankur@ex.com'; 
update users set start_topic_ids ="[2]" where email ='dino@ex.com';
